### ISSUE TITLE
[видео] Изучить, как показывать видео на телефоне

### ISSUE THREAD

**Issue by KoTius** [KoTius/YasnoMobileApp#2]
Тут 2 варианта:

1. У пользователя есть интернет, и он просто смотрит видосы как в ютубе. Тут или родной показ видео Андроидом (из инета? или надо чтобы файл был на девайсе?), или как-то использовать возможности Ютуб-апы.

2. 1. У пользователя нет интернета, и тогда нужно ему нажать кнопочку "скачать курс" — и весь курс стянется одним Bundle (пакетом \ набором \ архивом). Да, он потратит 100 Мб трафика и диского места, зато сможет смотреть в поезде\самолёте.

Свои мысли, как это реализуется, напиши, пожалуйста, в комменте к тикету.

**Comment by KoTius** [comment]
Так, тут есть детали к обсуждению.
Смотреть видео мы можем через ютуб, можно и без него, но, как мне кажется, The best way будет всё же именно через ютуб. Андроид = гугл = ютуб, роднее для юзеров.
Чтобы использовать ютуб апи должна быть установлена родная, для гугл сервисов, ютуб апа, но она идет вместе со всем паком гугл плей сервисов, так что тут ок.
Смотреть мы можем тремя вариантами:
1. Из нашей апы будет запускаться родная ютуб апа, и в ней уже будет проигрывать видео, как будто мы это видео вбили в поиск и нашли на ютубе. (как в браузере, если нажать на кнопочку youtube, то видео остановится и откроется сайт ютуба с видео.
2. Встроенный ютуб-проигрыватель в апу, по сути - то же самое как в браузере, я так понимаю, что это будет наш вариант.
3. Апа может запускать видео в некотором standalone плеере, я не разбирался с ним, похоже просто запускает отдельную активити и проигрывает в ней видео.
По сути - оно всё одно и тоже, просто разные подходы. Разве что, если использовать первый вариант, я так понимаю, что пользователю будут доступны стандартные функции, аля лайки, комментарии, нужно ли это там?
Далее сложнее. Ютуб протектит данные и не дает их скачивать. Я не уверен, возможно ли это вообще, но думаю возможно. Раз я могу смотреть, значит я могу и сохранить, нужно лишь найти способ.
Чтобы сохранить видео придется сделать некоторые вещи:
1. Тупо спарсить HTML страницы с нашим видео, достать ссылку на stream видео.
2. Декодировать эту ссылку.
3. Записать стрим в файл.
Тут есть нюансы. Парсинг - это статичная штука, если ютуб поменяет структуру HTML (Я правда не знаю, зачем бы они это делали, ведь все проги, которые парсят ютуб - умрут). В этом случае кому-то придется лезть в исходный код и адаптировать парсинг под новую структуру. С декодированием ссылки, наверное, та же история.
Мне этот вариант не очень нравится, ты говорил что-то про амазон. Ты можешь заливать туда файлы и я могу их качать прямой ссылкой или что-там?

**Comment by i1t2b3** [comment]
Сложную часть (парсить и всё такое) делать не нужно, ибо исходные файлы видео у нас есть.
Поэтому либо делаем вариант 2\3 с ютубом, либо заливаем файлы на хостинг (Амазон?) и проигрываем без всяких ютубов.

**Comment by KoTius** [comment]
Подожди, ты хочешь отказать от ютуба вообще?
Я думал смотреть с ютуба, а если качать, то уже с какого-то хостинга. Ведь я так понимаю, что всё видео и так будет на ютубе. Так, то мне, в принципе, всё равно. Но нужно определиться, чтобы я начал копать, как смотреть видео не через ютуб.

**Comment by i1t2b3** [comment]
Если видео-файл будет не на ютубе, как будет проигрываться видео?  В вебе просто используют HTML5-плеер, а в Андроиде что?

**Comment by KoTius** [comment]
Пока не знаю. Предположительно оно будет проигрываться точно тем же плеером, которым я бы проигрывал сохраненное видео (оффлайн режим), только буду проигрывать его онлайн, без сохранения потока.

**Comment by KoTius** [comment]
Собственно вопрос крайне простой. Либо мы работает с ютубом + хостинг сервисом (там будут некоторые связи, чтобы связать видео на ютубе с этим же видео для скачивания. Либо мы работаем без ютуба.

**Comment by KoTius** [comment]
Посмотрел свои папки, я разбирал медиа плеер в андроиде год назад, ничего там сложного не было. Всё может, может проигрывать как встроенные файлы, так и файлы на диске, так же и просто стримы с сети. Собственно говоря, хочешь ли ты интеграцию с ютубом или нет, вот весь вопрос.

**Comment by i1t2b3** [comment]
Давай пока выкинем функцию "скачать бандл и смотреть офлайн", так что в этой версии апы есть только просмотр с ютуба при наличии интернета.

**Comment by KoTius** [comment]
Уверен? А когда мы её вернем, как бы не оказалось, что нам нужно выкинуть ютуб и смотреть нативным андроид плеером :)
Хотя с другой стороны - в данном варианте мы не теряем особо человеко-часы, ибо с ютуб апи я уже почти разобрался (именно просмотр).

**Comment by i1t2b3** [comment]
Да, если смотреть нативным плеером, то делать придётся по-другому, на то она и "следующая версия". Давай пока ютуб юзать.

**Comment by KoTius** [comment]
Добро.

**Comment by KoTius** [comment]
Вот презентация, как можно смотреть видео с ютуба(про те варианты, запуск стедалон, ютубапа, встраивать), если интересно. Первые пять минут демонстрация, дальше уже технические детали.
