### ISSUE TITLE
Html.ImageGetter + asynctask

### ISSUE THREAD

**Issue by KoTius** [KoTius/YasnoMobileApp#22]
Не работает асинхронная загрузка изображений из клятого оштэмеля.

**Comment by KoTius** [comment]
Баг каверзный. Так-то эта загрузка работает, вот только при первом заходе в описание курса картинки не появятся. В отдельном потоке картинки успешно скачаются и никому об этом не скажут. При последующих заходах ImageGetter уже видит сохраненные картинки и использует их.

Нужно как-то сообщить этому ImageGetter'у, что картинки скачались и было бы неплохо их сразу использовать, только как это сделать - нет ни малейшего понятия.
Было бы весьма просто, если не использовать асинхронную загрузку, а грузить в основном потоке и пусть "весь мир подождёт", но если оборвётся интернет или сервер будет загружен, то апа, скорее всего, будет тупо висеть. Не ок так-то.

**Comment by i1t2b3** [comment]
А если стянуть картинки сразу когда получаем инфу по курсам?
