### ISSUE TITLE
Навигация мертва. Нужно уточнение.

### ISSUE THREAD

**Issue by KoTius** [KoTius/YasnoMobileApp#23]
Нужно оживить навигацию, работы тут до обеда, но нужно определиться.
На сайте навигация под шапкой курса, я думаю, было бы хорошо адаптироваться к специфике мобильного приложения.
1. Можно сделать как на сайте.
2. Можно сделать в Экшен баре приложения. Пользователям привычней видеть навигацию в экшен баре, но здесь есть свои подводные камень.
Очевидно, экшен бар ограничен шириной монитора, и он будет показывать столько элементов, сколько в него влезет, остальное уйдет в выпадающий список. Соответственно длинные записи "Все курсы", "Курсы этой категории" не поместятся "на виду".
Я могу указывать, что должно быть на виду всегда, а что если есть место. Но всё же тут вопрос дизайна. Если делать навигацию в шапке, то, как по мне, там должны быть иконки, понятные. Они и влезут заодно, но решать за тобой.
Опять же, работы там совсем немного, все данные у меня есть, нужно их только оживить он клик ивентами. Но делать так или эдак - это два абсолютно разных подхода со стороны кода.

**Comment by i1t2b3** [comment]
О какой навигации идёт речь? Можешь приложить скрин с сайта?

**Comment by KoTius** [comment]
Та, что в course details
http://SSMaker.ru/8ea4e9ef/
Вообще, её наличие весьма под вопросом на андроида.
Будет ли у нас "Главная страница" в мобайл?
Ссылка на "Все курсы" опять же весьма ненужна. Ибо будучи на course details - кнопка назад на самом девайсе вернет на "Все курсы", так же как и нативная кнопка в экшен баре андроида.
Думай.

**Comment by i1t2b3** [comment]
Это называется "хлебные крошки". Не надо их делать.

**Comment by KoTius** [comment]
Ок, тогда удалю то, что там уже накрошилось.
